#!/usr/bin/env python3
"""Generate the macOS app icon (SetMaster.icns) from the RML sunset mark (#214).

Authoring-time only. The generated .icns is committed to release/macos/, so
release/build-macos.sh never needs librsvg or this script. Re-run it only when
the mark or the plate changes:

    python3 tools/icon/make-icon.py

Requires rsvg-convert (brew install librsvg) and iconutil (Command Line Tools).

WHY THIS EXISTS RATHER THAN UPSCALING frontend/public/favicon.svg
-----------------------------------------------------------------
The favicon plate is a plain rounded rect at rx=27 on a 152 viewBox - 17.8%.
macOS uses a ~22.5% *superellipse* (squircle), which is a different curve, not
a different number, so no value of rx produces it.

macOS icons since Big Sur are also inset, not full-bleed: on a 1024 canvas the
plate occupies 824x824 centred, leaving 100px of transparent margin. Art drawn
edge-to-edge reads as oversized next to native apps in the Dock.

The mark's geometry and both gradients are copied verbatim from
docs/design/brand/rml-mark.svg. The plate colour #5B2E7E is the favicon's,
which sits between the mark's own #96409F and #2E2670 triangle stops.
"""

from __future__ import annotations

import math
import shutil
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
OUT_DIR = REPO_ROOT / "release" / "macos"
ICONSET = OUT_DIR / "SetMaster.iconset"
ICNS = OUT_DIR / "SetMaster.icns"
MASTER_SVG = OUT_DIR / "SetMaster-icon-1024.svg"

CANVAS = 1024          # macOS icon canvas
PLATE = 824            # Big Sur icon grid: the plate, centred, leaving 100px margin
SUPERELLIPSE_N = 5.0   # exponent approximating Apple's continuous corner
SAMPLES = 512          # points per quadrant; at 1024px this is visually exact

PLATE_FILL = "#5B2E7E"

# (size_px, filename) pairs iconutil expects in a .iconset
ICONSET_SIZES = [
    (16, "icon_16x16.png"),
    (32, "icon_16x16@2x.png"),
    (32, "icon_32x32.png"),
    (64, "icon_32x32@2x.png"),
    (128, "icon_128x128.png"),
    (256, "icon_128x128@2x.png"),
    (256, "icon_256x256.png"),
    (512, "icon_256x256@2x.png"),
    (512, "icon_512x512.png"),
    (1024, "icon_512x512@2x.png"),
]


def squircle_path(cx: float, cy: float, half: float, n: float, samples: int) -> str:
    """An SVG path for |x/half|^n + |y/half|^n = 1, centred on (cx, cy).

    Sampled rather than approximated with Beziers: the exact curve is cheap to
    evaluate and a dense polyline is indistinguishable from it at icon sizes,
    which avoids hand-tuned control points that only look right at one scale.
    """
    pts: list[tuple[float, float]] = []
    for i in range(samples * 4):
        theta = 2.0 * math.pi * i / (samples * 4)
        ct, st = math.cos(theta), math.sin(theta)
        # Signed superellipse parameterisation.
        x = half * math.copysign(abs(ct) ** (2.0 / n), ct)
        y = half * math.copysign(abs(st) ** (2.0 / n), st)
        pts.append((cx + x, cy + y))
    head = f"M {pts[0][0]:.3f} {pts[0][1]:.3f}"
    body = " ".join(f"L {x:.3f} {y:.3f}" for x, y in pts[1:])
    return f"{head} {body} Z"


def build_svg() -> str:
    plate = squircle_path(CANVAS / 2, CANVAS / 2, PLATE / 2, SUPERELLIPSE_N, SAMPLES)

    # rml-mark.svg draws in a 152x131 space with viewBox "24 4 152 131": the sun
    # spans x=28..172, the triangle y=86..131. Fit that box into the plate with
    # breathing room, matching the favicon's proportions (mark ~82% of plate).
    mark_w, mark_h = 144.0, 127.0     # 28..172 wide, 4..131 tall
    scale = (PLATE * 0.62) / mark_w
    mark_x = (CANVAS - mark_w * scale) / 2.0 - 28.0 * scale
    mark_y = (CANVAS - mark_h * scale) / 2.0 - 4.0 * scale

    return f"""<svg xmlns="http://www.w3.org/2000/svg" width="{CANVAS}" height="{CANVAS}" viewBox="0 0 {CANVAS} {CANVAS}">
  <!-- GENERATED by tools/icon/make-icon.py - do not hand-edit. See that file for why. -->
  <defs>
    <linearGradient id="rml-sun" x1="0" y1="8" x2="0" y2="80" gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="#E2836D"/>
      <stop offset="1" stop-color="#F0E5A6"/>
    </linearGradient>
    <linearGradient id="rml-tri" x1="0" y1="86" x2="0" y2="131" gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="#96409F"/>
      <stop offset="1" stop-color="#2E2670"/>
    </linearGradient>
  </defs>
  <path d="{plate}" fill="{PLATE_FILL}"/>
  <g transform="translate({mark_x:.3f} {mark_y:.3f}) scale({scale:.6f})">
    <path fill="url(#rml-sun)" d="M28 80 A72 72 0 0 1 172 80 Z"/>
    <path fill="url(#rml-tri)" d="M57 86 H143 L100 131 Z"/>
  </g>
</svg>
"""


def main() -> int:
    if not shutil.which("rsvg-convert"):
        print("ERROR: rsvg-convert not found. brew install librsvg", file=sys.stderr)
        return 1
    if not shutil.which("iconutil"):
        print("ERROR: iconutil not found (Command Line Tools).", file=sys.stderr)
        return 1

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    MASTER_SVG.write_text(build_svg(), encoding="utf-8")
    print(f"==> master SVG: {MASTER_SVG.relative_to(REPO_ROOT)}")

    if ICONSET.exists():
        shutil.rmtree(ICONSET)
    ICONSET.mkdir(parents=True)

    for size, name in ICONSET_SIZES:
        subprocess.run(
            ["rsvg-convert", "-w", str(size), "-h", str(size),
             "-o", str(ICONSET / name), str(MASTER_SVG)],
            check=True,
        )
    print(f"==> rendered {len(ICONSET_SIZES)} PNGs into {ICONSET.name}")

    subprocess.run(["iconutil", "-c", "icns", str(ICONSET), "-o", str(ICNS)], check=True)
    shutil.rmtree(ICONSET)
    print(f"==> {ICNS.relative_to(REPO_ROOT)}  ({ICNS.stat().st_size:,} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
