"""Comparison-notes snapshot-merge (comparison-output-table.md §5).

Hard requirement: a note on a row whose gap persists survives every pipeline
run, of any kind, without exception. Mechanism:

  1. snapshot notes before regeneration (caller passes the snapshot),
  2. after the pipeline regenerates joined CSVs, match each note's join key
     against the new rows,
  3. a note survives wherever the gap still exists (matched row's
     presence_flag != "Yes-Trak-Playlist"); resolved gaps drop + are counted,
  4. FAIL SAFE: deletes are deferred and applied in ONE transaction at the
     very end — an error of ANY kind anywhere in the merge leaves every note
     exactly as snapshotted (never regenerate-and-drop).

Notes for playlists whose joined CSV was NOT regenerated by this run (file
absent, or unchanged since before the run — compared by (mtime_ns, size)
signature, never wall-clock, which skews on Windows) are left untouched:
their comparison was not rebuilt, so there is nothing to merge against.
"""
from __future__ import annotations

import sqlite3
from pathlib import Path

from . import pipeline_data
from .pipeline_data import GAP_RESOLVED_FLAG


def joined_signatures(work_dir: Path) -> dict[str, tuple]:
    """(mtime_ns, size) per existing joined CSV — capture BEFORE the run."""
    out: dict[str, tuple] = {}
    joined = work_dir / "Joined"
    if joined.is_dir():
        for p in joined.glob("joined_*.csv"):
            st = p.stat()
            out[str(p)] = (st.st_mtime_ns, st.st_size)
    return out


def was_regenerated(path: Path, pre_run_sigs: dict[str, tuple]) -> bool:
    st = path.stat()
    return pre_run_sigs.get(str(path)) != (st.st_mtime_ns, st.st_size)


def merge_notes(
    conn: sqlite3.Connection,
    work_dir: Path,
    snapshot: list[dict],
    pre_run_sigs: dict[str, tuple],
) -> dict:
    """Merge snapshotted notes against regenerated joined CSVs.

    snapshot: [{slug, side, join_key, text}]; pre_run_sigs: joined_signatures()
    captured before the pipeline ran. Returns {restored, dropped, failed,
    error}. On any failure nothing is deleted and every snapshotted note is
    reported as restored.
    """
    try:
        by_slug: dict[str, list[dict]] = {}
        for n in snapshot:
            by_slug.setdefault(n["slug"], []).append(n)

        restored = 0
        to_drop: list[dict] = []
        for slug, notes in by_slug.items():
            joined = pipeline_data.find_joined_file(work_dir, slug)
            if joined is None or not was_regenerated(joined, pre_run_sigs):
                # comparison not regenerated this run -> notes untouched
                restored += len(notes)
                continue
            rows = pipeline_data.load_joined_rows(joined)
            # per side: join_key -> "some row with this key still has a gap"
            gap_by_key = {"spotify_trackjoin": {}, "trak_trackjoin": {}}
            for row in rows:
                flag = (row.get("presence_flag") or "").strip()
                persists = flag != GAP_RESOLVED_FLAG
                for col, keymap in gap_by_key.items():
                    k = (row.get(col) or "").strip()
                    if k:
                        keymap[k] = keymap.get(k, False) or persists
            for n in notes:
                # note in the Traktor column -> keyed on spotify_trackjoin;
                # note in the Spotify column -> keyed on trak_trackjoin
                col = "spotify_trackjoin" if n["side"] == "traktor" else "trak_trackjoin"
                if gap_by_key[col].get(n["join_key"], False):
                    restored += 1
                else:
                    to_drop.append(n)  # gap resolved or row gone

        with conn:  # single transaction: all-or-nothing
            for n in to_drop:
                conn.execute(
                    "DELETE FROM comparison_notes WHERE slug=? AND side=? AND join_key=?",
                    (n["slug"], n["side"], n["join_key"]),
                )
        return {"restored": restored, "dropped": len(to_drop), "failed": False, "error": None}
    except Exception as exc:  # noqa: BLE001 — fail safe on ANY merge failure
        return {
            "restored": len(snapshot),
            "dropped": 0,
            "failed": True,
            "error": f"{type(exc).__name__}: {exc}",
        }
